---
title: "PS270 Final Project"
author: "Kaushal Dasika"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

My research question for the Final Project is: How are the approval ratings of incumbent U.S. presidents running for the second term related to the stock market performance during their first term? My hypothesis is that higher stock market growth results in higher approval ratings going into a re-election. 
The hypothesis may be true as economic performance is a big talking point during elections and it makes sense that the voting public would be more receptive to the second term of a President that has shown economic growth. In this case, the variables of interest are the performance of the S&P 500 index, which is usually used to measure and gauge the development of the U.S. economy, and the approval ratings of an incumbent President going into re-election taken from the Roper Center. 
The approval rating variable will be measured by taking multiple sources (to ensure the overall representation is as accurate as possible) and will be compared to the S&P based on monthly changes in the index and approval ratings between the midterm and presidential elections (24 months). A pattern in the data that would prove my hypothesis is if positive and negative changes in the S&P translate to approval ratings and since the data will be measured over 2 years, it can account for before an incumbent declares they are running again. 
A pattern that would disprove is if there was no positive correlation on average across the 24-month period.


```{r}
library(readr)
library(tidyverse)
library(dplyr)
library(ggplot2)

pres <- read_csv("data/Presidential_Approval_Data.csv")
SP <- read_csv("data/SP500.csv")



pres <- pres |> 
  mutate(Month = as.character(Month))

SP <- SP |>
  mutate(Date = as.character(Date))


SP <- rename(SP, Month = Date)


result <- inner_join(pres, SP, by = "Month")

plot <- ggplot(data = result, aes(x = Price, y = Approving)) +
  geom_smooth() +
  labs(
    title = "Obama Approval Ratings vs S&P 500",
    x = "S&P 500",
    y = "Approval %"
  )

plot

```

